### ISSUE TITLE
Overwriting is not work! 

### ISSUE THREAD

**Issue by DuyenNguyen66** [outl1ne/nova-multiselect-field#199]
![image](https://user-images.githubusercontent.com/37392541/204247497-cfff432a-2ab2-4de1-a24e-81ad1c6d301f.png)
I added 1 file in resources/js/components like docs. But it's not work. Code in app.js is also not work.

Please write the docs more clearly, @Tarpsvo

**Comment by richard-raadi** [comment]
Hello!

If you have a step by step way of reproducing the issue you're facing, please provide one, otherwise we can not reproduce the issue you are facing.

The package documentation is sufficient for our team of developers to understand how it works. If you need more instructions on how to use this - feel free to open up a pull request to enhance new developer experience for other users after thoroughly introducing yourself on how it works.

If you are enjoying working with our open-source packages, please also consider sponsoring our team so that we can keep maintaining our software! 

I will however close this issue right now as there is no tangible issue mentioned in this thread.
